
export default new Map([
["src/content/books/test-book.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbooks%2Ftest-book.mdx&astroContentModuleFlag=true")],
["src/content/projects/spectre.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fspectre.mdx&astroContentModuleFlag=true")],
["src/content/other/about.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fother%2Fabout.mdx&astroContentModuleFlag=true")],
["src/content/posts/hmis-workshop-notes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fhmis-workshop-notes.mdx&astroContentModuleFlag=true")],
["src/content/posts/solving-leetcode-stone-game-iii.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fsolving-leetcode-stone-game-iii.mdx&astroContentModuleFlag=true")],
["src/content/posts/vps-lamp-setup-01-introduction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fvps-lamp-setup-01-introduction.mdx&astroContentModuleFlag=true")],
["src/content/posts/the-wealth-of-knowledge.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fthe-wealth-of-knowledge.mdx&astroContentModuleFlag=true")],
["src/content/posts/vps-lamp-setup-02-system-update-user-management.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fvps-lamp-setup-02-system-update-user-management.mdx&astroContentModuleFlag=true")],
["src/content/posts/vps-lamp-setup-03-install-lamp.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fvps-lamp-setup-03-install-lamp.mdx&astroContentModuleFlag=true")],
["src/content/posts/starting-to-use-neovim.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fstarting-to-use-neovim.mdx&astroContentModuleFlag=true")],
["src/content/posts/modern-problems-require-modern-solutions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fmodern-problems-require-modern-solutions.mdx&astroContentModuleFlag=true")]]);
		