
import __ASTRO_IMAGE_IMPORT_Z1BMdJT from "../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ftest-book.mdx";
import __ASTRO_IMAGE_IMPORT_1y8Vzg from "../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspectre.mdx";
import __ASTRO_IMAGE_IMPORT_Z1y9FeI from "assets/git-push/git_push.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcs50-codespace.mdx";
import __ASTRO_IMAGE_IMPORT_2roynt from "../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhmis-workshop-notes.mdx";
import __ASTRO_IMAGE_IMPORT_V8mvV from "assets/modern-problems/hype-cycle.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmodern-problems-require-modern-solutions.mdx";
import __ASTRO_IMAGE_IMPORT_AI91y from "assets/stone-game-iii/leet-code-scrshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsolving-leetcode-stone-game-iii.mdx";
import __ASTRO_IMAGE_IMPORT_Z1d9cDS from "assets/starting-to-use-neovim/neovim.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fstarting-to-use-neovim.mdx";
import __ASTRO_IMAGE_IMPORT_ZYXk1i from "assets/the-wealth-of-knowledge/03-ui.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-wealth-of-knowledge.mdx";
import __ASTRO_IMAGE_IMPORT_1ojHfk from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-01-introduction.mdx";
import __ASTRO_IMAGE_IMPORT_ZRbvqF from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-02-system-update-user-management.mdx";
import __ASTRO_IMAGE_IMPORT_1g3pC1 from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-03-install-lamp.mdx";
import __ASTRO_IMAGE_IMPORT_1tT5C1 from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-04-security-enhancements.mdx";
import __ASTRO_IMAGE_IMPORT_ZxeY53 from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-05-laravel-deployment-setup.mdx";
import __ASTRO_IMAGE_IMPORT_1wLK8w from "assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-06-domain-dns-ssl-setup.mdx";
export default new Map([["../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ftest-book.mdx", __ASTRO_IMAGE_IMPORT_Z1BMdJT], ["../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspectre.mdx", __ASTRO_IMAGE_IMPORT_1y8Vzg], ["assets/git-push/git_push.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcs50-codespace.mdx", __ASTRO_IMAGE_IMPORT_Z1y9FeI], ["../assets/spectre.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fhmis-workshop-notes.mdx", __ASTRO_IMAGE_IMPORT_2roynt], ["assets/modern-problems/hype-cycle.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmodern-problems-require-modern-solutions.mdx", __ASTRO_IMAGE_IMPORT_V8mvV], ["assets/stone-game-iii/leet-code-scrshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsolving-leetcode-stone-game-iii.mdx", __ASTRO_IMAGE_IMPORT_AI91y], ["assets/starting-to-use-neovim/neovim.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fstarting-to-use-neovim.mdx", __ASTRO_IMAGE_IMPORT_Z1d9cDS], ["assets/the-wealth-of-knowledge/03-ui.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fthe-wealth-of-knowledge.mdx", __ASTRO_IMAGE_IMPORT_ZYXk1i], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-01-introduction.mdx", __ASTRO_IMAGE_IMPORT_1ojHfk], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-02-system-update-user-management.mdx", __ASTRO_IMAGE_IMPORT_ZRbvqF], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-03-install-lamp.mdx", __ASTRO_IMAGE_IMPORT_1g3pC1], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-04-security-enhancements.mdx", __ASTRO_IMAGE_IMPORT_1tT5C1], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-05-laravel-deployment-setup.mdx", __ASTRO_IMAGE_IMPORT_ZxeY53], ["assets/vps-setup/terminal.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fvps-lamp-setup-06-domain-dns-ssl-setup.mdx", __ASTRO_IMAGE_IMPORT_1wLK8w]]);
		