url: "https://yethihahtwe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
title: "Blog|YeThiHaHtwe" # the name of your site, e.g. ACME Corp.
